### ISSUE TITLE
Read mode on horizions wrong on Windows

### ISSUE THREAD

**Issue by josephwinston** [joferkington/python-geoprobe#1]
```python
diff --git a/geoprobe/horizon.py b/geoprobe/horizon.py
index 9004de3..f462c7c 100644
--- a/geoprobe/horizon.py
+++ b/geoprobe/horizon.py
@@ -96,7 +96,7 @@ class horizon(object):

     def _readHorizon(self, filename):
         """Reads a horizon from disk"""
-        self._file = HorizonFile(filename, 'r')
+        self._file = HorizonFile(filename, 'rb')
         self._header = self._file.readHeader()

         if self._header == "#GeoProbe Horizon V2.0 ascii\n":
```

**Comment by joferkington** [comment]
Thanks for catching that!!  As you can see, I haven't tested things on Windows.

There are probably a lot of those around.  I'll crawl through things tonight and try to fix them.

**Comment by josephwinston** [comment]
As I find others that I can identify, I’ll let you know.

**Comment by joferkington** [comment]
I think 839b3f8ec8015dbf025aa6ee746d837212a11c17 fixes all of them.  I'm going to close this issue, but please re-open it or open another if you find any additional problems.

Thanks again!
