### ISSUE TITLE
file.vol

### ISSUE THREAD

**Issue by Andersongeofisco** [joferkington/python-geoprobe#5]
Hello! How can I make a .vol file?  Where can I find some information about it? Thanks!

**Comment by joferkington** [comment]
`.vol` is the on-disk seismic data format used by [GeoProbe](https://www.landmark.solutions/GeoProbe-Volume-Visualization) and [VoxelGeo](https://www.pdgm.com/products/voxelgeo/).  Typically, you'd use this library when reading in data written by one of those programs.  `python-geoprobe` is a library to handle reading and writing the file formats GeoProbe writes in python.

If you have a segy file that you'd like to load into memory as a numpy array, have a look at any of the various segy libraries (I'd recommend `segyio`).  Once you have it as a numpy array, you can write it out as a `.vol` file using this library if you'd like (e.g. `geoprobe.volume(data).write(filename)`).

**Comment by Andersongeofisco** [comment]
Many Thanks Joferkington.
